# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-16 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='message_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='user_id',
        ),
    ]
